version: "3"

services:

  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance-a11y:8080/Plone
      RAZZLE_API_PATH: http://localhost:8080/Plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance-a11y
    profiles:
      - prod

  backend-acceptance-a11y:
    image: ghcr.io/kitconcept/voltolighttheme:latest
    environment:
      CORS_: true
    ports:
      - 8080:8080
    profiles:
      - dev
      - prod
