const PUBLIC_PAGES = [
  '/content-types/page',
  '/content-types/image-light',
  '/content-types/event',
  '/block/heading-block',
  '/block/button-block',
  '/block/grid-block/text',
  '/block/grid-block/image',
  '/block/grid-block/teaser',
  '/block/grid-block/listing',
  '/block/highlight-block',
  '/block/image-block',
  '/block/listing-block',
  '/block/search-block',
  '/block/introduction-block',
  '/block/separator-block',
  '/block/teaser-block',
  '/block/table-block',
  '/block/text-block',
  '/block/video-block',
  '/block/toc-block',
  '/block/block-accordion',
  '/block/maps-block',
  '/vertical-spacing/grid-and-button',
  '/vertical-spacing/grid-and-grids',
  '/vertical-spacing/grid-and-text',
  '/vertical-spacing/heading-and-introduction',
  '/vertical-spacing/highlight-and-grid',
  '/vertical-spacing/highlight-and-text',
  '/vertical-spacing/listing-and-listing',
  '/vertical-spacing/listing-and-text',
  '/vertical-spacing/teasers-and-text',
  '/vertical-spacing/text',
  '/typography',
];

const PRIVATE_PAGES = ['/content-types/page'];

export { PUBLIC_PAGES, PRIVATE_PAGES };
