version: '3.3'

services:

  frontend:
    image: ghcr.io/kitconcept/voltolighttheme-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://lighttheme-kitconcept-io_backend:8080/Plone
    depends_on:
      - backend
    networks:
      - public
    healthcheck:
      disable: true
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == app
          - node.labels.env == staging
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.svc-lighttheme-stg-front.loadbalancer.server.port=3000
        # Middlewares
        # Routers
        ## lighttheme.kitconcept.io
        - traefik.http.routers.rt-lighttheme-stg-front.rule=Host(`lighttheme.kitconcept.io`)
        - traefik.http.routers.rt-lighttheme-stg-front.entrypoints=https
        - traefik.http.routers.rt-lighttheme-stg-front.tls=true
        - traefik.http.routers.rt-lighttheme-stg-front.tls.certresolver=le
        - traefik.http.routers.rt-lighttheme-stg-front.service=svc-lighttheme-stg-front
        - traefik.http.routers.rt-lighttheme-stg-front.middlewares=gzip

  backend:
    image: ghcr.io/kitconcept/voltolighttheme:latest
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
          - node.labels.env == staging
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.svc-lighttheme-stg-backend.loadbalancer.server.port=8080
        # Middleware
        - "traefik.http.middlewares.mw-lighttheme-stg-backend-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.mw-lighttheme-stg-backend-vhm.replacepathregex.replacement=/VirtualHostBase/https/lighttheme.kitconcept.io/Plone/++api++/VirtualHostRoot/$$1"
        # Router ++api++
        - traefik.http.routers.rt-lighttheme-stg-backend.rule=Host(`lighttheme.kitconcept.io`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.rt-lighttheme-stg-backend.entrypoints=https
        - traefik.http.routers.rt-lighttheme-stg-backend.tls=true
        - traefik.http.routers.rt-lighttheme-stg-backend.service=svc-lighttheme-stg-backend
        - traefik.http.routers.rt-lighttheme-stg-backend.middlewares=gzip,mw-lighttheme-stg-backend-vhm

networks:
  public:
    external: true
    driver: overlay
