name: Backend Image Generation

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      plone-version:
        required: true
        type: string
      push:
        required: true
        type: boolean


jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 8080:8080 ${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:${{ inputs.base-tag }}
          flavor:
            latest=false
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=${{ inputs.base-tag }}
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image to Registry
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: backend/
          file: backend/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:buildcache-${{ inputs.base-tag }}
          cache-to: type=registry,ref=${{ inputs.image-name-prefix }}-${{ inputs.image-name-suffix }}:buildcache-${{ github.ref_name }},mode=max
          build-args: |
            PLONE_VERSION=${{ inputs.plone-version }}
            SEED=$GITHUB_RUN_ID
