name: Backend Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      plone-version:
        required: true
        type: string

defaults:
  run:
    working-directory: backend

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ inputs.python-version }}
      PLONE_VERSION: ${{ inputs.plone-version }}
    steps:

        - name: Checkout
          uses: actions/checkout@v6

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v8.1.0
          with:
            python-version: ${{ inputs.python-version }}
            cache-suffix: ${{ inputs.plone-version }}

        - name: Install Plone and package
          run: make install

        - name: Run tests
          run: make test
