name: Documentation

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    working-directory: docs

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: false

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}-${{ inputs.python-version }}

      - name: Install Dependencies
        run: make install

      - name: Check for broken links
        run: make linkcheckbroken

      - name: Build HTML documentation
        run: make build
