name: Documentation

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    working-directory: docs

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        run: make install

      - name: Check for broken links
        run: make linkcheckbroken

      - name: Build HTML documentation
        run: make build
