name: Frontend Visual acceptance tests
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  acceptance:
    uses: ./.github/workflows/visual-acceptance.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Homepage"
            short-name: homepage
          - name: "Content"
            short-name: content
          - name: "Blocks A"
            short-name: blocks-A
          - name: "Blocks B"
            short-name: blocks-B
          - name: "Blocks Grid"
            short-name: blocks-grid
          - name: "Blocks Listing"
            short-name: blocks-listingsandsearch
          - name: "Vertical Spacing"
            short-name: vertical-spacing
          - name: "Typography"
            short-name: typography
    name: ${{ matrix.name }}
    with:
      short-name: ${{ matrix.short-name }}
      node-version: ${{ inputs.node-version }}
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-tag: ${{ inputs.image-tag }}
